### ISSUE TITLE
ContentNotFoundError

### ISSUE THREAD

**Issue by ITcafee** [GladistonXD/html2pdfconverter#2]
C:\Users\AVI\Desktop\html2pdfconverter-main>python html2pdfconverter.py --path "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe" --input perlego.html --output perlego.pdf --page-size A4
Traceback (most recent call last):
  File "C:\Users\AVI\Desktop\html2pdfconverter-main\html2pdfconverter.py", line 148, in <module>
    html_to_pdf(processed_html, args.output, args.path, args.page_size)
  File "C:\Users\AVI\Desktop\html2pdfconverter-main\html2pdfconverter.py", line 135, in html_to_pdf
    pdfkit.from_string(processed_html, pdf_file, configuration=config, options=options)
  File "C:\Users\AVI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pdfkit\api.py", line 75, in from_string
    return r.to_pdf(output_path)
  File "C:\Users\AVI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pdfkit\pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "C:\Users\AVI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pdfkit\pdfkit.py", line 155, in handle_error
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: ContentNotFoundError

**Comment by GladistonXD** [comment]
It looks like a folder permission error to me, try moving "wkhtmltopdf.exe" to the same folder as the rest of the files

**Comment by ITcafee** [comment]
Done, but same error again and again

**Comment by GladistonXD** [comment]
How is the command running?

**Comment by ITcafee** [comment]
![Untitled](https://github.com/user-attachments/assets/5ad9d00b-e52f-4918-9884-a385f4eead89)

**Comment by GladistonXD** [comment]
The problem is in the "perlego.html" file, this converter only works in the "EPUB" format, books in PDF format are not compatible.
